### ISSUE TITLE
Add a test function for daily_std in inflammation/models.py

### ISSUE THREAD

**Issue by douglas-m-harvey** [rowan04/python-intermediate-inflammation#9]

**Comment by rowan04** [comment]
Was done, just was in develop branch, not main. Have merged now.

**Comment by Wikyboy** [comment]
Test was implemented in test/models: 
https://github.com/rowan04/python-intermediate-inflammation/blob/18e09a4c394ee58cbedb53e2db976bc8fb37765f/tests/test_models.py#L54-L57
